project:
  type: website
  output-dir: docs

website:
  navbar:
    background: black
    foreground: gray-100
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - mycv.qmd
      #- teaching.qmd
      #- research.qmd 
   
format:
  html:
    theme: darkly.css
    toc: true