project:
  type: website
  output-dir: docs

website:
  sidebar:
    background: black
    foreground: gray-100
    style: "docked"
    search: true
    contents:
      - section: "About Me"
        contents:
          - text: "Home"
            href: index.qmd
          - mycv.qmd
          - text: "Students' Work"
            href: https://umdfiresa.github.io
      #- teaching.qmd
      #- research.qmd
      - text: "---"
      - section: "Resources"
        contents:
          - text: "HYSPLIT with R"
            href: hysplit.qmd
          - text: "Workflow with R & GitHub"
            href: r-and-github.qmd
          - text: "Paper Replication ASNs"
            href: paper-replication.qmd
   
format:
  html:
    theme: darkly.css
    toc: true