project:
  type: website
  output-dir: docs

website:
  sidebar:
    background: gray-900
    foreground: gray-100
    style: "docked"
    search: true
    contents:
      - section: "About Me"
        contents:
          - text: "Home"
            href: index.qmd
          - mycv.qmd

      #- teaching.qmd
      #- research.qmd
    
      - text: "---"
      - section: "Resources"
        contents:
          - text: "HYSPLIT with R"
            href: hysplit.qmd
          - text: "Workflow with R & GitHub"
            href: r-and-github.qmd
          - text: "Paper Replication ASNs"
            href: paper-replication.qmd
            
      - text: "---"
      - section: "External Site "
        contents:
          - text: "Students' Work"
            href: https://umdfiresa.github.io
   
format:
  html:
    theme: darkly.css
    toc: true